import pandas as pd
import sys

# Path to the CSV file relative to the project root
csv_file_path = 'public/data/ipl_data.csv'

def escape_sql_string(s):
    """Escapes single quotes in a string for SQL insertion."""
    return s.replace("'", "''")

try:
    # Read the CSV file
    df = pd.read_csv(csv_file_path)

    # Extract unique team and venue names
    all_teams = pd.unique(df[['batting_team', 'bowling_team']].values.ravel('K')).tolist()
    all_venues = df['venue'].unique().tolist()

    # Sort the lists for consistency
    all_teams.sort()
    all_venues.sort()

    # Generate SQL for teams, with escaped names
    teams_sql = "INSERT INTO public.teams (name) VALUES\n"
    teams_sql += ",\n".join([f"('{escape_sql_string(team)}')" for team in all_teams]) + ";\n"
    
    # Generate SQL for venues, with escaped names
    venues_sql = "\nINSERT INTO public.venues (name) VALUES\n"
    venues_sql += ",\n".join([f"('{escape_sql_string(venue)}')" for venue in all_venues]) + ";\n"

    # Print the full SQL script
    print(f"-- Generated by generate_seed_sql.py on {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(teams_sql)
    print(venues_sql)

except FileNotFoundError:
    print(f"Error: The file '{csv_file_path}' was not found.", file=sys.stderr)
    sys.exit(1)
except Exception as e:
    print(f"An unexpected error occurred: {e}", file=sys.stderr)
    sys.exit(1)