// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjzrzbhkaxuelionlpct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqenJ6YmhrYXh1ZWxpb25scGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjUzMjMsImV4cCI6MjA3NDA0MTMyM30.PDFhC4k5JK1u54VEVmREzrmwm2LKscVaWNyAKJmKV78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});